"""Command-line interface for deterministic screening runs."""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
from pathlib import Path
from typing import Sequence

from stocks_infer.algorithms import registry
from stocks_infer.config import AppConfig
from stocks_infer.dataset import fingerprint_screening_records
from stocks_infer.models import RunManifest
from stocks_infer.recorded_data import load_screening_records
from stocks_infer.runner import ScreeningRunner
from stocks_infer.storage import ParquetSnapshotStore, RunArtifactStore, StorageLayout


def build_parser(config: AppConfig) -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="stocks-infer",
        description="Run reproducible, explainable stock screens.",
    )
    commands = parser.add_subparsers(dest="command", required=True)

    commands.add_parser(
        "list-algorithms", help="List registered screening algorithms."
    )

    fixture = commands.add_parser(
        "screen-fixture",
        help="Run algorithms against a recorded canonical JSON dataset.",
    )
    fixture.add_argument("--input", type=Path, required=True)
    fixture.add_argument(
        "--output-root", type=Path, default=config.output_root
    )
    fixture.add_argument(
        "--shortlist-size", type=int, default=config.shortlist_size
    )
    fixture.add_argument(
        "--minimum-algorithms",
        type=int,
        help="Minimum successful algorithm scores required for consensus; defaults to all.",
    )
    fixture.add_argument(
        "--algorithm",
        action="append",
        choices=registry.names(),
        help="Algorithm to run; repeat the option to select several. Defaults to all.",
    )
    fixture.add_argument(
        "--run-id",
        help="Stable run identifier. A timestamped identifier is generated by default.",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    config = AppConfig.from_environment()
    parser = build_parser(config)
    arguments = parser.parse_args(argv)

    if arguments.command == "list-algorithms":
        for algorithm in registry.all():
            print(f"{algorithm.slug} {algorithm.version} - {algorithm.description}")
        return 0

    if arguments.command == "screen-fixture":
        return _screen_fixture(arguments)

    parser.error(f"unknown command: {arguments.command}")
    return 2


def _screen_fixture(arguments: argparse.Namespace) -> int:
    records = load_screening_records(arguments.input)
    as_of_dates = {record.as_of_date for record in records}
    if len(as_of_dates) != 1:
        raise ValueError("all fixture records must have the same as-of date")
    as_of_date = as_of_dates.pop()

    algorithms = registry.select(arguments.algorithm)
    minimum_algorithms = arguments.minimum_algorithms or len(algorithms)
    parameters = {
        "shortlist_size": arguments.shortlist_size,
        "minimum_algorithms": minimum_algorithms,
    }
    runner = ScreeningRunner(algorithms)
    result = runner.run(
        records,
        as_of_date=as_of_date,
        shortlist_size=arguments.shortlist_size,
        minimum_algorithms=minimum_algorithms,
        parameters=parameters,
    )

    started_at = datetime.now(timezone.utc)
    run_id = arguments.run_id or (
        f"{as_of_date.isoformat()}-{started_at.strftime('%Y%m%dT%H%M%S%fZ')}"
    )
    layout = StorageLayout(arguments.output_root)
    parquet = ParquetSnapshotStore()
    dataset_fingerprint = fingerprint_screening_records(records)
    normalized_path = (
        layout.normalized_directory(as_of_date)
        / dataset_fingerprint
        / "screening_records.parquet"
    )
    if not normalized_path.exists():
        parquet.write_screening_records(normalized_path, records)

    sources = tuple(
        sorted(
            {
                source
                for record in records
                for source in (record.fundamentals_source, record.price_source)
            }
        )
    )
    manifest = RunManifest(
        schema_version=1,
        run_id=run_id,
        started_at=started_at,
        as_of_date=as_of_date,
        universe=f"recorded-fixture:{arguments.input.name}",
        dataset_fingerprint=dataset_fingerprint,
        input_snapshot=str(normalized_path.relative_to(arguments.output_root)),
        data_sources=sources,
        algorithms=tuple(
            {"slug": algorithm.slug, "version": algorithm.version}
            for algorithm in algorithms
        ),
        parameters=parameters,
        evaluated_count=len(records),
        shortlisted_count=len(result.shortlist),
    )
    artifact_store = RunArtifactStore(layout, parquet)
    run_directory = artifact_store.write(
        manifest=manifest,
        all_scores=result.algorithm_scores + result.consensus_scores,
        shortlist=result.shortlist,
    )

    print(f"Normalized snapshot: {normalized_path}")
    print(f"Run artifacts: {run_directory}")
    print("Shortlist:")
    for score in result.shortlist:
        print(f"  {score.rank:>3}  {score.ticker:<8} {score.score:>7.2f}")
    return 0
