"""Command-line interface for deterministic screening runs."""

from __future__ import annotations

import argparse
from datetime import date, datetime, timezone
import json
from pathlib import Path
from typing import Sequence

from stocks_infer.algorithms import registry
from stocks_infer.config import AppConfig
from stocks_infer.dataset import fingerprint_screening_records
from stocks_infer.models import RunManifest
from stocks_infer.recorded_data import load_screening_records
from stocks_infer.runner import ScreeningRunner
from stocks_infer.storage import ParquetSnapshotStore, RunArtifactStore, StorageLayout


def build_parser(config: AppConfig) -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="stocks-infer",
        description="Run reproducible, explainable stock screens.",
    )
    commands = parser.add_subparsers(dest="command", required=True)

    commands.add_parser(
        "list-algorithms", help="List registered screening algorithms."
    )

    research = commands.add_parser("research", help="Create dated company research reports from a recorded historical bundle.")
    research.add_argument("--input", type=Path, required=True)
    research.add_argument("--as-of", type=date.fromisoformat, required=True)
    research.add_argument("--output-root", type=Path, default=config.output_root)
    research.add_argument("--run-id")
    compare = commands.add_parser("research-compare", help="Compare two saved research reviews and verify their artifacts.")
    compare.add_argument("--before", type=Path, required=True)
    compare.add_argument("--after", type=Path, required=True)

    sec_pilot = commands.add_parser("import-sec-pilot", help="Normalize reviewed SEC annual and quarterly concepts for development and difficult cases.")
    sec_pilot.add_argument("--universe", type=Path, required=True)
    sec_pilot.add_argument("--ticker-map", type=Path, required=True)
    sec_pilot.add_argument("--company-facts", action="append", required=True, metavar="TICKER=PATH")
    sec_pilot.add_argument("--as-of", type=date.fromisoformat, required=True)
    sec_pilot.add_argument("--retrieved-on", type=date.fromisoformat, default=date.today())
    sec_pilot.add_argument("--output", type=Path, required=True)

    development = commands.add_parser("import-sec-development", help="Normalize all 30 Development companies from saved SEC Company Facts.")
    development.add_argument("--universe", type=Path, required=True)
    development.add_argument("--ticker-map", type=Path, required=True)
    development.add_argument("--company-facts-dir", type=Path, required=True)
    development.add_argument("--as-of", type=date.fromisoformat, required=True)
    development.add_argument("--retrieved-on", type=date.fromisoformat, default=date.today())
    development.add_argument("--output", type=Path, required=True)

    fixture = commands.add_parser(
        "screen-fixture",
        help="Run algorithms against a recorded canonical JSON dataset.",
    )
    fixture.add_argument("--input", type=Path, required=True)
    fixture.add_argument(
        "--output-root", type=Path, default=config.output_root
    )
    fixture.add_argument(
        "--shortlist-size", type=int, default=config.shortlist_size
    )
    fixture.add_argument(
        "--minimum-algorithms",
        type=int,
        help="Minimum successful algorithm scores required for consensus; defaults to all.",
    )
    fixture.add_argument(
        "--algorithm",
        action="append",
        choices=registry.names(),
        help="Algorithm to run; repeat the option to select several. Defaults to all.",
    )
    fixture.add_argument(
        "--run-id",
        help="Stable run identifier. A timestamped identifier is generated by default.",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    config = AppConfig.from_environment()
    parser = build_parser(config)
    arguments = parser.parse_args(argv)

    if arguments.command == "list-algorithms":
        for algorithm in registry.all():
            print(f"{algorithm.slug} {algorithm.version} - {algorithm.description}")
        return 0

    if arguments.command == "screen-fixture":
        return _screen_fixture(arguments)

    if arguments.command == "research":
        from stocks_infer.research.artifacts import write_research_run

        destination = write_research_run(arguments.input, arguments.output_root, arguments.as_of, arguments.run_id)
        print(f"Research review: {destination / 'README.md'}")
        print(f"Comparison: {destination / 'comparison.csv'}")
        return 0

    if arguments.command == "research-compare":
        from stocks_infer.research.artifacts import compare_runs

        print(json.dumps(compare_runs(arguments.before, arguments.after), indent=2))
        return 0

    if arguments.command == "import-sec-pilot":
        from stocks_infer.research.io import write_json
        from stocks_infer.research.sec_companyfacts import companyfacts_bundle, load_sec_payloads
        from stocks_infer.research.universe import load_universe, match_sec_identifiers

        if arguments.output.exists():
            raise FileExistsError(f"normalized bundle already exists: {arguments.output}")
        universe = load_universe(arguments.universe)
        payloads = load_sec_payloads(arguments.company_facts)
        ticker_map = json.loads(arguments.ticker_map.read_text(encoding="utf-8"))
        identifiers = match_sec_identifiers(
            tuple(company for company in universe if company.ticker in payloads), ticker_map
        )
        bundle = companyfacts_bundle(
            universe, identifiers, payloads,
            as_of=arguments.as_of, retrieved_on=arguments.retrieved_on,
        )
        arguments.output.parent.mkdir(parents=True, exist_ok=True)
        write_json(arguments.output, bundle)
        print(f"Normalized {len(bundle.companies)} companies and {len(bundle.facts)} SEC facts: {arguments.output}")
        return 0

    if arguments.command == "import-sec-development":
        from stocks_infer.research.io import write_json
        from stocks_infer.research.sec_companyfacts import companyfacts_bundle
        from stocks_infer.research.universe import load_universe, match_sec_identifiers

        if arguments.output.exists():
            raise FileExistsError(f"normalized bundle already exists: {arguments.output}")
        development_companies = tuple(
            company for company in load_universe(arguments.universe)
            if company.test_set == "Development"
        )
        ticker_map = json.loads(arguments.ticker_map.read_text(encoding="utf-8"))
        identifiers = match_sec_identifiers(development_companies, ticker_map)
        payloads = {
            company.ticker: json.loads((arguments.company_facts_dir / f"{company.ticker}-companyfacts.json").read_text(encoding="utf-8"))
            for company in development_companies
        }
        bundle = companyfacts_bundle(
            development_companies, identifiers, payloads,
            as_of=arguments.as_of, retrieved_on=arguments.retrieved_on,
        )
        arguments.output.parent.mkdir(parents=True, exist_ok=True)
        write_json(arguments.output, bundle)
        print(f"Normalized {len(bundle.companies)} Development companies and {len(bundle.facts)} SEC facts: {arguments.output}")
        return 0

    parser.error(f"unknown command: {arguments.command}")
    return 2


def _screen_fixture(arguments: argparse.Namespace) -> int:
    records = load_screening_records(arguments.input)
    as_of_dates = {record.as_of_date for record in records}
    if len(as_of_dates) != 1:
        raise ValueError("all fixture records must have the same as-of date")
    as_of_date = as_of_dates.pop()

    algorithms = registry.select(arguments.algorithm)
    minimum_algorithms = arguments.minimum_algorithms or len(algorithms)
    parameters = {
        "shortlist_size": arguments.shortlist_size,
        "minimum_algorithms": minimum_algorithms,
    }
    runner = ScreeningRunner(algorithms)
    result = runner.run(
        records,
        as_of_date=as_of_date,
        shortlist_size=arguments.shortlist_size,
        minimum_algorithms=minimum_algorithms,
        parameters=parameters,
    )

    started_at = datetime.now(timezone.utc)
    run_id = arguments.run_id or (
        f"{as_of_date.isoformat()}-{started_at.strftime('%Y%m%dT%H%M%S%fZ')}"
    )
    layout = StorageLayout(arguments.output_root)
    parquet = ParquetSnapshotStore()
    dataset_fingerprint = fingerprint_screening_records(records)
    normalized_path = (
        layout.normalized_directory(as_of_date)
        / dataset_fingerprint
        / "screening_records.parquet"
    )
    if not normalized_path.exists():
        parquet.write_screening_records(normalized_path, records)

    sources = tuple(
        sorted(
            {
                source
                for record in records
                for source in (record.fundamentals_source, record.price_source)
            }
        )
    )
    manifest = RunManifest(
        schema_version=1,
        run_id=run_id,
        started_at=started_at,
        as_of_date=as_of_date,
        universe=f"recorded-fixture:{arguments.input.name}",
        dataset_fingerprint=dataset_fingerprint,
        input_snapshot=str(normalized_path.relative_to(arguments.output_root)),
        data_sources=sources,
        algorithms=tuple(
            {"slug": algorithm.slug, "version": algorithm.version}
            for algorithm in algorithms
        ),
        parameters=parameters,
        evaluated_count=len(records),
        shortlisted_count=len(result.shortlist),
    )
    artifact_store = RunArtifactStore(layout, parquet)
    run_directory = artifact_store.write(
        manifest=manifest,
        all_scores=result.algorithm_scores + result.consensus_scores,
        shortlist=result.shortlist,
    )

    print(f"Normalized snapshot: {normalized_path}")
    print(f"Run artifacts: {run_directory}")
    print("Shortlist:")
    for score in result.shortlist:
        print(f"  {score.rank:>3}  {score.ticker:<8} {score.score:>7.2f}")
    return 0
